export const GET_SMURFS_SUCCESS = "GET_SMURFS";
export const LOADING_START = "LOADING_START";
export const GET_SMURFS_ERROR = "GET_SMURFS_ERROR";
export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const POPULATE_FORM = "POPULATE_FORM";
